-  name: cart module
   hosts: cart
   enabled: yes
   tasks:
   -  name: disable and enable cart module
      ansible.builtin.shell: dnf module disable nodejs -y ;  dnf module enable nodejs:20 -y

   -  name: install node js
      ansible.builtin.dnf:
          name: nodejs
          state: present

   -  name: create roboshop user
      ansible.builtin.user:
          name: roboshop
   
   -  name: delete app directory
      ansible.builtin.file:
          path: /app
          state: absent
   
   -  name: create app directory
      ansible.builtin.file:
          path: /app
          state: directory

   -  name: download cart data
      ansible.builtin.get_url:
          url: https://roboshop-builds.s3.amazonaws.com/cart.zip
          path: /tmp

   -  name: extract data
      ansible.builtin.unarchive:
          src: /tmp/cart/zip
          dest: /app
          remote_src: yes

   -  name: install npm
      ansible.builtin.command:  npm install
      args:
          chdir: /app

   -  name: create  cart service
      ansible.builtin.copy: 
          src: cart.service
          dest: /etc/systemd/system/cart.service


   -  name:  reload daemon
      ansible.builtin.systemd_service:
          daemon_reload: true

   -  name: start and enable cart
      ansible.builtin.service:
          name: cart
          state: restarted
          enabled: yes

